#!/bin/bash
# Script que impacta la configuracion de Squid Adaptativa y hace 
# efectivo el cambio del IPSEC.
#
# Version 1.1 - Mayo 2015
#
# Proyectos Especiales.
# Gerencia de tecnologia.
# Banco Credicoop Coop. Ltdo.

PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
. /usr/local/bin/squid-conf.lib

CreaConf

/usr/sbin/ipsec update
/usr/local/bin/fix-snmpd.sh
