#!/bin/bash
#
# Genera la solicitud para el certificado X.509.
# Este script lo ejecuta el confelace.py
#
# Diego Woitasen - XTECH
# 2011
# Luis Vinay - XTECH
# 2013
#
# rev: 201306101401
#
#      201301241129: Cambiamos CN por FQDN
#      201306101401: Actualizamos los links para Puppet
#      

export ALTNAME=DNS:nodovpn${1}.bancocredicoop.coop
export CN=nodovpn${1}.bancocredicoop.coop

OUT=/etc/ipsec.d/reqs/nodovpn${1}.pem 

openssl req -config /etc/crediconn/openssl.cnf \
	-keyout /etc/ipsec.d/private/nodovpn${1}-key.pem \
	-out $OUT \
	-new -nodes -days 9999 -batch > /dev/null 2>&1

if [ $? -ne 0 ]; then
	dialog --msgbox "Fallo la generacion del certificado" 10 60
	exit 1
fi

dialog --msgbox "Solicitud generada: $OUT. Una vez que se firma, el certificado va en /etc/ipsec.d/certs/nodovpn${1}-cert.pem" 10 60

# Genero los links para los certs SSL de Puppet
/usr/local/bin/gen-puppet-ssl-links.sh $1

exit 0
