- name: Asegurar que el directorio existe
  file: 
    path: '/etc/squid3'
    state: directory 

- name: "Build QoS"
  template:
    src: templates/squid3.conf.j2
    dest: "/etc/squid3/squid_{{link.name}}.conf"
    owner: root
    group: root
    mode: '0644'
  vars:
  - segundos_libres_individual: 2
  - segundos_libres_global: 3
  - cuota_individual: '{{link.intranet_bandwidth_down}} / 8 * {{segundos_libres_individual}} * 1024'
  - cuota_global: '{{link.intranet_bandwidth_down}} / 8 * {{segundos_libres_global}} * 1024 '
    # ACLs => bulk-QoS-REG: ZIMBRA
  - bw_individual_intranet: '{{link.intranet_bandwidth_down}} / 8 * {{link.bw_procentaje_individual_intranet}} / 100 * 1024'
  - bw_global_intranet: '{{link.intranet_bandwidth_down}} / 8 * {{link.bw_procentaje_global_intranet}} / 100 *1024'
    # ACLs => InternetSinBandaHoraria-FQDN,  InternetBandaHoraria-FQDN, InternetSinBandaHoraria-REG
  - bw_individual_internet: '{{link.internet_bandwidth_down}} / 8 * {{link.bw_procentaje_individual_internet}} / 100 * 1024'
  - bw_global_internet: '{{link.internet_bandwidth_down}} / 8 * {{link.bw_procentaje_global_internet}} / 100 * 1024'
  when: intranet_bandwidth_down > 0 and internet_bandwidth_down > 0

- name: "QoS legacy squid"
  file:
    path: '/etc/squid3/squid_{{link.name}}.conf'
    src: /etc/squid3/squid_estatico.conf
    state: link
  when: intranet_bandwidth_down <= 0 or internet_bandwidth_down <= 0