- hosts: "{{host_override | default('all')}}" 
  vars:
    local_users_group:
      name: admin
      id: 20000
      filename: admin
      comment: Usuario de emergencia local - integrado SATAUC
      filecontent: |
        # Permisos otorgados para el Usuario de emergencia local - integrado SATAUC
        # v1 (puppet nodo v5.1) - 3-08-2018
        #
        # Proyectos Especiales.
        # Gerencia de tecnologia.
        # Banco Credicoop Coop. Ltdo.

        # Ejecucion sin clave para el reinicio de servicio puppet.
        comunica ALL=(ALL) NOPASSWD: /etc/cron.daily/puppetd

        # Escalada en privilegios mediante clave.
        %admin ALL=(ALL) ALL
    
    sudofilesnmp: |
      # Ejecuciones de servicio para el listado de estado via remota.
      #
      # Proyectos Especiales.
      # Gerencia de tecnologia.
      # Banco Credicoop Coop. Ltdo.

      snmp ALL=(ALL) NOPASSWD: /usr/sbin/ipsec, /etc/crediconn/scripts/netmap_status, /etc/crediconn/scripts/balanceo_status, /usr/local/bin/credicfg.py
    
    logindefs: |
      ARCHIVO DE PUPPET -> 2018 - Agosto 13.
      MAIL_DIR        /var/mail
      FAILLOG_ENAB		yes
      LOG_UNKFAIL_ENAB	no
      LOG_OK_LOGINS		yes
      SYSLOG_SU_ENAB		yes
      SYSLOG_SG_ENAB		yes
      SULOG_FILE	/var/log/sulog
      FTMP_FILE	/var/log/btmp
      SU_NAME		su
      HUSHLOGIN_FILE	.hushlogin
      ENV_SUPATH	PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      ENV_PATH	PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      # Reemplazado -> ENV_PATH	PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
      TTYGROUP	tty
      TTYPERM		0600
      ERASECHAR	0177
      KILLCHAR	025
      # UMASK		027 -> Reemplazado a pedido de rlaurin (segurinf).
      UMASK		077
      PASS_MAX_DAYS	99999
      PASS_MIN_DAYS	0
      PASS_WARN_AGE	7
      UID_MIN			 1000
      UID_MAX			60000
      GID_MIN			 1000
      GID_MAX			60000
      LOGIN_RETRIES		3
      LOGIN_TIMEOUT		60
      CHFN_RESTRICT		rwh
      DEFAULT_HOME	yes
      USERGROUPS_ENAB yes
      ENCRYPT_METHOD SHA512

    sudofilesatcon: |
      #
      # Usuario a pedido de Segurinf. Dic-2016
      #
      # Proyectos Especiales.
      # Gerencia de tecnologia.
      # Banco Credicoop Coop. Ltdo.

      User_Alias USRSATAUC	= satcscon

      Cmnd_Alias CMDSATAUC	= /usr/bin/passwd
      Cmnd_Alias CMDAPPSCONSOLA	= /bin/cat,/usr/bin/find,/usr/bin/stat

      USRSATAUC	ALL = NOPASSWD: CMDSATAUC
      apps_consola	ALL = (ALL) NOPASSWD: CMDAPPSCONSOLA
      #

    users_for_delete:
    - aorieta
    - cdamiano

    permissions:
    - name: acsi
      groupid: '2020'
      userlist:
      - {name: aalvarez, uid: 10002}
      - {name: hheller, uid: 11002}
      - {name: jmartin, uid: 11004}
      - {name: abalzarini, uid: 11014}
      - {name: acgarcia, uid: 11008}
      - {name: gdezaedeleer, uid: 11017}
      - {name: ngrinblat, uid: 13015}
      - {name: rlaurin, uid: 15047}
      usercomment: Usuario de segurinf
      sudocomment: Pedido por Seguninf. Dic-2016.
      sudoversion: 1 (puppet nodo v5.1) - 8-08-2018
      sudocommandalias: Cmnd_Alias CMD_SEGINF     = /bin/cat, /bin/chmod, /bin/chown, /bin/more, /bin/rm, /usr/bin/find, /usr/bin/passwd, /usr/bin/sudo, /usr/bin/vi, /usr/sbin/groupadd, /usr/sbin/groupmod, /usr/sbin/useradd, /usr/sbin/userdel, /usr/sbin/usermod, /usr/sbin/visudo, /sbin/iptables-restore, /bin/cp, /sbin/iptables, /bin/vi, /usr/sbin/tcpdump
      sudouseralias: "# No hay user alias"
      sudopermission: "%acsi	ALL=(ALL)  NOPASSWD: CMD_SEGINF"
    - name: mantell
      groupid: '20005'
      userlist:
      - {name: equiroga, uid: 13026}
      - {name: sgasparini, uid: 13007}
      usercomment: GerCom - Mantenimiento de telefonia
      sudocomment: Permisos otorgados para Mantenimiento de Redes, perteneciente a GerCom.
      sudoversion: 1 (puppet nodo v5.1) - 8-08-2018
      sudocommandalias: Cmnd_Alias CMDTEL	= /bin/ping
      sudouseralias: "# No hay user alias"
      sudopermission: "%manttel ALL=(ALL) NOPASSWD: CMDTEL"        
    - name: mantredes
      groupid: '20001'
      userlist:
      - {name: rmaldonado, uid: 13011}
      - {name: piglesias, uid: 13018}
      - {name: jalvarez, uid: 13005}
      - {name: mmourino, uid: 13025}
      - {name: mkippes, uid: 13040}
      - {name: gpperez, uid: 10003}
      usercomment: GerCom - Mantenimiento de redes
      sudocomment: Permisos otorgados para Mantenimiento de Redes, perteneciente a GerCom.
      sudoversion: 1 (puppet nodo v5.1) - 8-08-2018
      sudocommandalias: "# No aplica command alias"
      sudouseralias: "# No hay user alias"
      sudopermission: "%mantredes ALL=(ALL) ALL"       
    - name: implementaciones
      groupid: '20002'
      userlist:
      - {name: mgrosso, uid: 13010}
      - {name: jmidaberry, uid: 5059}
      - {name: pmolas, uid: 13019}
      - {name: dcaffarena, uid: 13024}
      - {name: psanchez, uid: 13021}
      - {name: amolina, uid: 13038}
      - {name: dsantacruz, uid: 13037}
      - {name: nspagnuolo, uid: 13020}
      - {name: rediaz, uid: 14243}
      - {name: cvardanega, uid: 13030}
      usercomment: GerCom - Implementaciones
      sudocomment: Permisos otorgados para el sector Implementaciones, perteneciente a GerCom.
      sudoversion: 1 (puppet nodo v5.1) - 8-08-2018
      sudocommandalias: "# No aplica command alias"
      sudouseralias: "# No hay user alias"
      sudopermission: "%implementaciones ALL=(ALL) ALL" 
    - name: mantfiliales
      groupid: '20003'
      userlist:
      - {name: cdreiling, uid: 13004}
      - {name: amultisanti, uid: 13008}
      - {name: pcupello, uid: 13009}
      - {name: cmoretto, uid: 13041}
      - {name: wguimerans, uid: 13043}
      - {name: fcorrali, uid: 13045}
      usercomment: GerCom - Mantenimiento de filiales
      sudocomment: Permisos otorgados para el sector Mantenimiento de filiales, perteneciente a GerCom.
      sudoversion: 1 (puppet nodo v5.1) - 8-08-2018
      sudocommandalias: "# No aplica command alias"
      sudouseralias: "# No hay user alias"
      sudopermission: "%mantfiliales ALL=(ALL) ALL" 
    - name: atusu
      groupid: '20004'
      userlist:
      - {name: rpacheco, uid: 13006}
      - {name: dhsampallo, uid: 13039}
      - {name: ccarletti, uid: 13042}
      - {name: mmquesada, uid: 13044}
      - {name: mgebhart, uid: 13046}
      - {name: dmancini, uid: 13049}
      - {name: gtulissi, uid: 13050}
      - {name: tzedde, uid: 13051}
      usercomment: GerCom - Atencion a usuarios
      sudocomment: Permisos otorgados para el sector de atencion a usuarios, perteneciente a GerCom.
      sudoversion: 1 (puppet nodo v5.1) - 8-08-2018
      sudocommandalias: Cmnd_Alias CMDATUSU	= /bin/ping
      sudouseralias: "# No hay user alias"
      sudopermission: "%atusu ALL=(ALL) NOPASSWD: CMDATUSU" 
    - name: proyesp
      groupid: '1203'
      userlist:
      - {name: mgiannini, uid: 13033}
      - {name: amartin, uid: 13031}
      - {name: gperezbrun, uid: 13003}
      - {name: aamicucci, uid: 2016}
      - {name: nlobarinas, uid: 5047}
      usercomment: GerTec - Proyectos especiales
      sudocomment: Permisos otorgados para el sector Proyectos especiales, perteneciente a GerTec.
      sudoversion: 1 (puppet nodo v5.1) - 8-08-2018
      sudocommandalias: "# No aplica command alias"
      sudouseralias: "# No hay user alias"
      sudopermission: "%proyesp ALL=(ALL) ALL" 
      
  tasks:
  - name: Provisionar sudoers
    include_role:
      name: file-provision
    vars:
      applyConffilial: true
      owner: 'root'
      group: 'root'
      mode: '0440'
      path: '/etc'
      files: 
      - 'sudoers'

  # Local users
  - name: Sudofile para local users presente
    copy:
      content: "{{local_users_group.filecontent}}"
      dest: "/etc/sudoers.d/{{local_users_group.filename}}"
      owner: root
      group: root
      mode: '0440'

  - name: Grupo para local users presente
    group:
      name: "{{local_users_group.name}}"
      gid: "{{local_users_group.id}}"
      state: present
  
  - name: Usuario comunica presente
    user:
      name: comunica
      comment: "{{local_users_group.comment}}"
      shell: /bin/bash
      groups: "{{local_users_group.name}}"
      create_home: yes
      uid: 1000
      password: '$6$LyNYCz99$AuPm8CUDYEHW27alkD1ZD33RB2LpaGkbXlTmPSfDLPXkcMAT.doSJ9lfFecM.6tbOxqJnWzr4xkhu2whG1ZpU.'
  
  - name: Modificar password root
    user:
      name: root
      password: '$6$i2uQuat1$DZo49/0/luqYe155hd0OS89CklKSxI3PUyet13523zXwUNmvtVkRSDSWL59JSjoEvMpFz.HTc83QcPHbhy2pT.'

  # Archivo de sudo para servicio SNMP (consulta de estado)
  - name: Sudofile para servicio SNMP presente
    copy:
      content: "{{sudofilesnmp}}"
      dest: "/etc/sudoers.d/snmp"
      owner: root
      group: root
      mode: '0440'
    notify: Reiniciar servicio sudo

  - name: login.defs presente
    copy:
      content: "{{logindefs}}"
      dest: "/etc/login.defs"
      owner: root
      group: root
      mode: '0644'

  - name: Permisos (700) a /home/*
    file:
      path: /home/*
      state: directory
      mode: '0700'
      recurse: yes
  
  # Se deshabilita la consola tty9 en modo debug-> es una TTY sin login con permisos de ROOT.
  - name: debug-shell.service ausente
    file:
      path: /etc/systemd/system/sysinit.target.wants/debug-shell.service
      state: absent
    notify: Desactivar debug shell

  # Borrado de usuarios
  - name: Usuarios borrados
    user: 
      name: "{{item}}"
      state: absent
    loop: "{{users_for_delete}}"

  # Segurinf
  - name: Usuario satcscon presente
    user:
      name: satcscon
      uid: '11010'
      comment: 'Usuario para uso de SatAuc'
      create_home: yes
      shell: /bin/bash
    notify: Reiniciar servicio sudo
  
  - name: Sudofile para satcscon presente
    copy:
      content: "{{sudofilesatcon}}"
      dest: "/etc/sudoers.d/satauc"
      owner: root
      group: root
      mode: '0440'

  - name: Usuario apps_consola presente
    user:
      name: satcscon
      uid: '1029'
      comment: 'Usuario de servicio para segurinf'
      create_home: yes
      shell: /bin/bash
      groups: users

  # https://docs.ansible.com/ansible/2.9/modules/authorized_key_module.html
  - name: Setear ssh key para apps_consola
    authorized_key:
      user: apps_consola
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAIEAqaNfynJumuvC4xhCGVWnE+smth9tY144J6vS0mwt8H62GJVsei1ZfVMxM45KkApL2i8OxZ63pRnhwQS5aXYy6DCKw6luw11ayEpV0xqVFZYBzpMVMrRCC/2TSWa1aNr98clE8cSlZEbzYON6C5ChwqdXByE+Gxi084IMinnFXbc="

  - name: Impactar permisos
    include_role:
      name: impacta-permisos
    vars:
      permission: '{{item}}'
    loop: '{{permissions}}'

  handlers:
  - name: Reiniciar servicio sudo
    service: 
      name: sudo
      state: restarted
    listen: 
    - Restart sudo service
    - post file provision

  # Se deshabilita la consola tty9 en modo debug-> es una TTY sin login con permisos de ROOT.
  - name: Desactivar debug shell
    shell: systemctl stop debug-shell.service ; systemctl disable debug-shell.service