- hosts: "{{host_override | default('all')}}" 
  vars:
    BINARIES_VERSION: 4.3.1-6+deb8u4
  tasks:
    # DHCP-CLIENT 
    - name: Provisionar configuraciones
      include_role:
        name: file-provision
      vars:
        applyConffilial: true
        owner: root
        group: root
        mode: '644'
        files: 
        - path: /etc/dhcp
          name: dhclient.conf
        - path: /usr/local/bin
          name: credi-iface-up.sh
          group: staff
          mode: '755'
        - path: /etc/crediconn/templates
          name: network-interfaces-dhcp
          group: staff
        
    - name: Instalar paquetes DHCP
      apt:
        pkg:
        - 'isc-dhcp-client={{BINARIES_VERSION}}'
        
    # DHCP-SERVER 
    - name: Provisionar template
      include_role:
        name: file-provision
      vars:
        applyConffilial: true
        owner: root
        group: root
        path: /etc/crediconn/templates
        mode: '644'
        files:
        - dhcpd.conf

    - name: Provisionar configuraciones
      include_role:
        name: file-provision
      vars:
        owner: root
        group: root
        mode: '640'
        path: '/etc/dhcp'
        files:
        - dhcpd-ip-fijas.conf
        - dhcpd-subclass-notebooks.conf
        - dhcpd-subclass-telefonosfijos.conf
        - dhcpd-subclass-switches.conf

    - name: Instalar paquetes dhcp server
      apt:
        pkg:
        - 'isc-dhcp-common={{BINARIES_VERSION}}'
        - 'isc-dhcp-server={{BINARIES_VERSION}}'
 
  handlers:
  - name: Asegurar que isc-dhcp-server este corriendo
    service:
      name: isc-dhcp-server
      state: started
      enabled: true
    listen: post conffilial apply