- hosts: "{{host_override | default('all')}}" 
  tasks:
    - name: Provisionar configuraciones
      include_role:
        name: file-provision
      vars:
        owner: 'root'
        group: 'root'
        mode: '644'
        path: '/etc'
        files: 
        - 'resolv.conf' 
        - 'dhcp/dhclient-enter-hooks.d/nodnsupdate'

    - name: Actualizar hostfile (/etc/hosts)
      lineinfile: 
        dest: /etc/hosts 
        regexp: '.*{{ item }}$' 
        line: "{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" 
        state: present
      with_items:
        - name: '{{ansible_facts.facter_hostname}}'
          ip: '{{ansible_facts.facter_ipaddress_eth0}}'
        - name: localhost
          ip: 127.0.0.1