- hosts: "{{host_override | default('all')}}" 
  vars:
      PKG_VERSION: 5.2.1-6+deb8u8

  tasks:
    - name: Actualizar templates ipsec
      include_role:
        name: file-provision
      vars:
        applyConffilial: true
        owner: 'root'
        group: 'root'
        mode: '640'
        path: '/etc/crediconn/templates'
        files: 
        # Lista de templates basicos.
        - ipsec_up
        - ipsec.secrets
        - ipsec.conf
        # Lista de templates de conectividad por Drago.
        - ipsec.conf-drago-fase1
        - ipsec.conf-drago-fase2
        - ipsec.conf-drago-fase1-dhcp
        - ipsec.conf-drago-fase2-dhcp
        # Lista de templates de conectividad por Vera.
        - ipsec.conf-vera-fase1
        - ipsec.conf-vera-fase2
        - ipsec.conf-vera-fase1-dhcp
        - ipsec.conf-vera-fase2-dhcp

    - name: Actualizar repositorios
      copy:
        dest: '/etc/apt/sources.list.d/security.list'
        content: 'deb http://srep4001lx.bancocredicoop.coop:9999/security jessie/updates main non-free contrib'
        owner: root
        group: root
        mode: 640

    - name: Instalar paquetes
      apt:
        update_cache: yes 
        pkg:
        - strongswan={{ PKG_VERSION }}
        - strongswan-charon={{ PKG_VERSION }}
        - strongswan-ike={{ PKG_VERSION }}
        - strongswan-libcharon={{ PKG_VERSION }}
        - strongswan-starter={{ PKG_VERSION }}
    
  handlers:
    - name: Acualizar daemon strongswan
      shell: "ipsec update"
      listen: post conffilial apply