- hosts: "{{host_override | default('all')}}" 
  tasks:
    - name: Provisionar configuraciones
      include_role:
        name: file-provision
      vars:
        owner: 'root'
        group: 'root'
        mode: '644'
        path: '/etc/network'
        files: 
        - iptables.filter.rules
        - iptables.mangle.rules

    
    - name: Asegurar ausencia de iptables.filter.ori
      file:
        path: '/etc/network/iptables.filter.ori'
        state: absent
        owner: root
        group: root
        mode: 644
      notify: Aplicar filtro

  handlers:
    - name: Aplicar filtro
      shell:
        cmd: "iptables-restore < /etc/network/iptables.filter.rules"
      notify: Aplicar mangle
      listen: post file provision

    - name: Aplicar mangle
      shell:
        cmd: "iptables-restore < /etc/network/iptables.mangle.rules"
      notify:
      - Aplicar dscp eth1
      - Aplicar dscp eth2

    - name: Aplicar dscp eth1 
      shell:
        cmd: '$(/bin/cat /etc/network/interfaces|grep -v "\#"|grep "ADD --NIC eth1"|grep MarcasPaquetes|sed "s/\tpost-up //g")'

    - name: Aplicar dscp eth2
      shell:
        cmd: '$(/bin/cat /etc/network/interfaces|grep -v "\#"|grep "ADD --NIC eth2"|grep MarcasPaquetes|sed "s/\tpost-up //g")'        