- hosts: "{{host_override | default('all')}}" 
  tasks:
    - name: Fetch variables
      include_vars:
        dir: roles/file-provision/defaults

    # Provisionar archivos
    - name: Provisionar puppet.conf
      copy:
        src: "{{ FILESRC }}/etc/puppet/puppet.conf"
        dest: "/etc/puppet/puppet.conf"
        owner: root
        group: admin
        mode: 644
      notify:
      - Asegurar que cliente puppet este corriendo
    
    - name: Provisionar credicoopnodo.rb
      copy:
        src: "{{ FILESRC }}/usr/lib/ruby/vendor_ruby/facter/credicoopnodo.rb"
        dest: "/usr/lib/ruby/vendor_ruby/facter/credicoopnodo.rb"
        owner: root
        group: admin
        mode: 550

    # - name: Provisionar credbicoop_info_nodo
    #   file:
    #     src: "{{ FILESRC }}/etc/crediconn/templates/credicoop_info_nodo"
    #     dest: "/etc/crediconn/templates/credicoop_info_nodo"
    #     owner: root
    #     group: admin
    #     mode: 644
    #   notify:
    #   - Aplicar template
  
  handlers:
    - name: Asegurar que cliente puppet este corriendo
      service:
        name: puppet
        state: started
        enabled: true

    # - name: Aplicar template
    #   shell:
    #     cmd: "[ -e /etc/credicoop_info_nodo.ini  ] && conffilial.py apply"

    # class puppetclient_20180807::hostsdns {
    #  host { 'puppetmaster.bancocredicoop.coop' :
    #   ensure => 'present',
    #   target => '/etc/hosts',
    #   ip => '10.7.10.73',
    #   host_aliases => 'puppetmaster',
    #  }
    # }
