- hosts: "{{host_override | default('all')}}"
  tasks:
  - name: Provisionar purga
    include_role:
      name: file-provision
    vars:
      owner: 'root'
      group: 'root'
      path: '/usr/local/bin/'
      files: 
      - name: PurgaSquid.sh
        mode: '0755'
      - name: PurgaSquid.txt
        mode: '0744'

  handlers:
  - name: Aplicar purga
    shell:  /usr/local/bin/PurgaSquid.sh > /tmp/PurgaSquid.log 2>&1
    listen: post file provision