- hosts: "{{host_override | default('all')}}"
  vars:
    primario_bandwidth_down: 512
    secundario_bandwidth_down: 512
    intranet_bandwidth_down: 512
    internet_bandwidth_down: 512
  tasks:

  # Setear version de squid
  - set_fact:
      VERSION_SQUID: '3.4.8-6+deb8u9'
    when: ansible_facts.facter_is_virtual is defined and ansible_facts.facter_is_virtual == 'true'

  - set_fact:
      VERSION_SQUID: '3.4.8-6+deb8u5'
    when: ansible_facts.facter_is_virtual is not defined or ansible_facts.facter_is_virtual != 'true'

  # Servicio
  - name: Asegurar que squid3 este corriendo 
    service:
      name: squid3
      state: started
      enabled: true

  # QoS
  # Construir QoS
  - name: "Estatico"
    include_role:
      name: qos-build
    vars:
      link:
        name: 'estatico'
        bw_procentaje_individual_intranet: 39
        bw_procentaje_global_intranet: 50
        bw_procentaje_individual_internet: 25
        bw_procentaje_global_internet: 35
        intranet_bandwidth_down: 512
        internet_bandwidth_down: 512
    notify: Reload squid3
  
  # Ejecuta la task solo si es un archivo regular
  - name: Change the working directory to somedir/ before executing the command
    shell: /usr/bin/test ! -h /etc/squid3/squid.conf
    register: file_test

  - name: Change the working directory to somedir/ before executing the command
    shell: /bin/ln -sf /etc/squid3/squid_estatico.conf /etc/squid3/squid.conf
    when: file_test is defined and file_test.rc == 0

  # Templates
  - name: "Ambos enlaces definidos"
    include_role:
      name: qos-build
    vars:
      link: '{{item}}'
    when: secundario_provider_name is defined and primario_provider_name is defined
    loop:
    - name: "dos_vinculos"
      bw_procentaje_individual_intranet: 39
      bw_procentaje_global_intranet: 50
      bw_procentaje_individual_internet: 60
      bw_procentaje_global_internet: 100
      intranet_bandwidth_down: '{{primario_bandwidth_down}}'
      internet_bandwidth_down: '{{secundario_bandwidth_down}}'
    - name: "primario"
      bw_procentaje_individual_intranet: 39
      bw_procentaje_global_intranet: 50
      bw_procentaje_individual_internet: 25
      bw_procentaje_global_internet: 35
      intranet_bandwidth_down: '{{primario_bandwidth_down}}'
      internet_bandwidth_down: '{{primario_bandwidth_down}}'
    - name: "secundario"
      bw_procentaje_individual_intranet: 39
      bw_procentaje_global_intranet: 50
      bw_procentaje_individual_internet: 25
      bw_procentaje_global_internet: 35
      intranet_bandwidth_down: '{{secundario_bandwidth_down}}'
      internet_bandwidth_down: '{{secundario_bandwidth_down}}'
    notify: Reload squid3

  - name: "Solo enlace primario definido"
    include_role:
      name: qos-build
    vars:
      link:
        name: '{{item}}'
        bw_procentaje_individual_intranet: 39
        bw_procentaje_global_intranet: 50
        bw_procentaje_individual_internet: 25
        bw_procentaje_global_internet: 35
        intranet_bandwidth_down: '{{primario_bandwidth_down}}'
        internet_bandwidth_down: '{{primario_bandwidth_down}}'
    when: secundario_provider_name is not defined and primario_provider_name is defined
    loop:
    - dos_vinculos
    - primario
    - secundario
    notify: Reload squid3

  - name: "Solo enlace secundario definido"
    include_role:
      name: qos-build
    vars:
      link:
        name: '{{item}}'
        bw_procentaje_individual_intranet: 39
        bw_procentaje_global_intranet: 50
        bw_procentaje_individual_internet: 25
        bw_procentaje_global_internet: 35
        intranet_bandwidth_down: '{{secundario_bandwidth_down}}'
        internet_bandwidth_down: '{{secundario_bandwidth_down}}'
    when: secundario_provider_name is defined and primario_provider_name is not defined
    loop:
    - dos_vinculos
    - primario
    - secundario
    notify: Reload squid3

  - name: "Ningun enlace definido"
    include_role:
      name: qos-build
    vars:
      link:
        name: '{{item}}'
        bw_procentaje_individual_intranet: 39
        bw_procentaje_global_intranet: 50
        bw_procentaje_individual_internet: 25
        bw_procentaje_global_internet: 35
        intranet_bandwidth_down: 512
        internet_bandwidth_down: 512
    when: secundario_provider_name is not defined and primario_provider_name is not defined
    loop:
    - dos_vinculos
    - primario
    - secundario
    notify: Reload squid3

  # Configuracion
  ## Archivos estaticos    
  - name: Borrar archivo de prueba
    file:
      path: '/etc/squid3/PruebaMensajeInternet.squid.conf'
      state: absent

  - name: Provisionar archivos estaticos
    include_role:
      name: file-provision
    vars:
      owner: 'root'
      group: 'root'
      mode: '644'
      dirmode: '0755'
      path: '/etc/squid3'
      files:
      # Hasta que se desafecte la vieja clase de puppet hay que comentario
      - 'GSACollectionArgentina.694.squid.conf'
      - 'VNGlobal.587.squid.conf'
      - 'Datco.602.squid.conf'
      - 'DirectGroup.690.squid.conf'
      - 'EstudioMartinezDeAlzaga.691.squid.conf'
      - 'Segurcoop.803.squid.conf'
      - 'GellerAbogados.657.squid.conf'
      # Bandas horarias
      - 'GrupoHorario_.txt'
      - 'cache_peers_proxyfil.conf'
      - 'cache_peers_wanproxy.conf'
      - 'squid.acl.conf'
      # Template
      - name: squid3.conf.erb
        path: /usr/local/bin
    notify: Reload squid3
  
  # Binarios
  - name: Actualizar repositorios
    copy:
      dest: '/etc/apt/sources.list.d/squidsecurity.list'
      content: 'deb http://srep4001lx.bancocredicoop.coop:9999/security jessie/updates main non-free contrib'
    notify: Actualizar squid3
    
  - name: Remover squid
    file:
      path: /etc/init.d/squid
      state: absent
    notify: Limpiar squid startup legacy

  - name: Paquetes de squid
    apt:
      update_cache: yes
      name: '{{item}}'
      state: present
    loop:
    - 'squid3={{VERSION_SQUID}}'
    - 'squid3-common={{VERSION_SQUID}}'
    - 'squidclient={{VERSION_SQUID}}'
  
  handlers:
  - name: Aplicar QoS
    shell: '/etc/crediconn/scripts/squid_qos.sh --qos'
    notify: Reload squid3
  
  - name: Actualizar squid3
    shell: 'update-rc.d -f squid3 remove ; update-rc.d squid3 enable'

  - name: Reload squid3
    shell: '/usr/sbin/squid3 -k reconfigure'