- hosts: localhost
  tasks:
  - name: Verificar que se hay aprovisto un host_override
    fail:
      msg: "Recuerde definir el grupo sobre el cual desea ejecutar. Por ejemplo: ansible-playbook nodosPiloto.yml --extra-vars 'host_override=workstations'"
    when: host_override is not defined

  - name: Advertencia de ejecucion sobre grupo no esperado
    fail: 
      msg: "Esta intentando ejecutar sobre un grupo distinto a: piloto. Si es lo que desea realizar, desabilite o edite esta tarea del playbook"
    when: host_override != "workstations"

- import_playbook: adminusers.yml
- import_playbook: dhcpd.yml
- import_playbook: wanproxy.yml
# - import_playbook: openntpd.yml
- import_playbook: bind9dns.yml
# - import_playbook: copia_archivos.yml
# - import_playbook: etc_crediconn.yml
# - import_playbook: cron.yml
- import_playbook: iptables.yml
- import_playbook: puppetclient.yml
# - import_playbook: snmp_nodovpn.yml
# - import_playbook: rsyslog.yml
- import_playbook: squid3.yml
- import_playbook: purga_squid.yml