- hosts: "{{host_override | default('all')}}" 
  tasks:
    - name: Provisionar configuraciones
      include_role:
        name: file-provision
      vars:
        owner: 'root'
        group: 'root'
        mode: '644'
        path: '/etc/init.d'
        files: 
        - 'wanproxy'

  handlers:
    - name: Purgar
      shell:
        cmd: "/etc/init.d/wanproxy purgedb"
      listen: post file provision
