#!/bin/bash
# Scrip de desactivacion de balanceo.
#
# Version 1.1.1 - Marzo-2017
#       Se agrega compatibilidad con Squid v3 -> NodoVPN v5.1
#
# Version 1.1 - 8-05-2015
#       Se agrega QoS diferencial para Squid ante balanceo.
#       Despliegue via puppet.
#
# Proyectos Especiales.
# Gerencia de tecnología.
# Banco Credicoop Coop. Ltdo.

PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

iptables -t nat -F BALANCEO

# Verifico si es Squid v3
squid3 -v 2> /dev/null 1>/dev/null
if [ $? -eq 0 ] ; then
        HomeSquid="/etc/squid3"
else
        HomeSquid="/etc/squid"
fi
if [ -h $HomeSquid/squid.conf ] ; then
	/etc/crediconn/scripts/squid_qos.sh --qos
fi

