#!/bin/bash
# Scrip de activación de balanceo.
#
# Version 1.2.1 - Marzo-2017
#       Compatilibilidad con Squid v3 -> NodoVPN v5.1
#
# Version 1.2 - 6-05-2015
#       Se agrega QoS diferencia ante balanceo.
#       Despliegue via puppet.
#
# Proyectos Especiales.
# Gerencia de tecnología.
# Banco Credicoop Coop. Ltdo.

PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

iptables -t nat -A BALANCEO -p tcp --dport 3128 -j VERA_NETMAP

# Verifico si es Squid v3
squid3 -v 2> /dev/null 1>/dev/null
if [ $? -eq 0 ] ; then
        HomeSquid="/etc/squid3"
else
        HomeSquid="/etc/squid"
fi
if [ -h $HomeSquid/squid.conf ] ; then
        # Si es un link simbolico, entiendo que tengo que cambiar QoS.
        /etc/crediconn/scripts/squid_qos.sh --qos
fi
