#!/bin/bash
# Version 1.2 (Marzo.2017)
# 	Se agrega compatibilidad con Squid v3 -> Nodo V5.1
# Version 1.1 (2015)
# 	Se agrega squid_QoS para garantizar el estado adecuado del squid.conf
#
# Proyectos Especiales.
# Gerencia de tecnologia.
# Banco Credicoop Coop. Ltdo.

PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"


# Verifico si es Squid v3
squid3 -v 2> /dev/null 1>/dev/null
if [ $? -eq 0 ] ; then
        HomeSquid="/etc/squid3"
else
        HomeSquid="/etc/squid"
fi
if [ -h $HomeSquid/squid.conf ] ; then
	/etc/crediconn/scripts/squid_qos.sh --qos
fi


timeout -k 20 10 ipsec statusall

if [ $? -eq 124 ]; then
	/usr/local/bin/credilog.py "ipsec status timeout, haciendo update"
	ipsec update
fi
